contracts/compiled/contract_tester.py
contracts/compiled/contractlib/contractlib.py
contracts/compiled/contractlib/mintlib.py
contracts/compiled/contractlib/secretlib/secretlib.py
contracts/compiled/contractlib/snip20lib.py

_Overview_
* Created base functions for interacting with the secretcli
* Created a base contract class to store all contract values
* Added a Snip20 implementation of said class with basic support for our tests (will probably be expanded at a later time)
* Added a Mint implementation along with all of its Handles and Queries
_Details_
The new testing script contains functions that automate using the secretcli. Using these functions is a new base contract class that can be expanded with the necessary functionality to abstract users writing tests as much as possible.

Improved Scripted Contract Testing

---

README.md
compile-contracts.sh
contracts/README.md
contracts/mint/README.md
contracts/mint/src/contract.rs

_Overview_
* Main readme now reflect current repo code
* Mint readme contains all of the contracts functions
_Details_
Documented information for ease of use in the future

Added Mint contract documentation

---

README.md

For running the contracts locally

Update Readme Dev ENV

---

contractlib/micro_mintlib.py
contracts/micro_mint/README.md
contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/query.rs
contracts/micro_mint/src/state.rs
contracts/micro_mint/src/test.rs
packages/shade_protocol/src/micro_mint/mod.rs
tester.py

Minting commissions will now vary per asset instead of per native asset

micro-mint commission overhaul

---

contracts/micro_mint/README.md
contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/query.rs
contracts/micro_mint/src/state.rs
packages/shade_protocol/src/micro_mint/mod.rs

Updated the documentation for the micro_mint
Also renamed some functions/structs to conform to the rest of the contracts

Micro mint documentation

---

contracts/oracle/README.md

First in a series of commits to update the documentation.
Please don't merge yet, I will keep adding to this PR and the additions can be reviewed piecemeal.

Add to documentation

---

contractlib/oraclelib.py
contractlib/secretlib/secretlib.py
contracts/micro_mint/src/handle.rs
contracts/mint/src/contract.rs
contracts/mock_band/src/contract.rs
contracts/oracle/README.md
contracts/oracle/src/contract.rs
contracts/oracle/src/handle.rs
contracts/oracle/src/query.rs
contracts/oracle/src/state.rs
makefile
packages/shade_protocol/src/oracle.rs
test-index.py
test-oracle.py

Initial testing looks good, I can test more thoroughly once we have BAND on pulsar-1. Currently uses a basic weighted average
```
price | weight
1.00  | .5
7.5    | .5
sum((price * weight), ...) / total_weight = price
((1.0 * .5) + (7.5 * .5)) / (.5 + .5) = 4.25
```
```
price | weight
1.00  | .2
7.5    | .5
sum((price * weight), ...) / total_weight = price
((1.0 * .2) + (7.5 * .5)) / (.2 + .5) = 5.642857142857143
```
I used this site to build test cases https://www.rapidtables.com/calc/math/weighted-average-calculator.html
This still needs testing with sswap pairs and such, but using band it is working well

Oracle index

---

contracts/airdrop/README.md
contracts/initializer/README.md
contracts/initializer/src/contract.rs
contracts/initializer/src/query.rs
contracts/micro_mint/README.md
contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/mock_band/Cargo.toml
packages/shade_protocol/src/initializer.rs
packages/shade_protocol/src/micro_mint.rs

Updated some contract documentation

Documentation | contract updates

---

contracts/governance/Cargo.toml
contracts/governance/src/contract.rs
contracts/governance/src/lib.rs
contracts/governance/src/query.rs
contracts/governance/src/test.rs
packages/shade_protocol/src/governance/mod.rs

Closes https://github.com/securesecrets/shade/issues/136
Hello guys, recently I've started looking into Rust and thought I'd check out Shade protocol code,
decided to try to implement this feature (seemed like a "good first issue"), so here it is,
if you've got some time for this, any feedback would be welcome :)
Side-note: maybe I should refactor my unit-tests a bit to get rid of duplicated code ?

[governance] Query proposals by status

---

contracts/airdrop/Cargo.toml
contracts/airdrop/README.md
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
packages/network_integration/Cargo.toml
packages/network_integration/tests/testnet_integration.rs
packages/secretcli/src/secretcli.rs
packages/shade_protocol/Cargo.toml
packages/shade_protocol/src/airdrop/account.rs
packages/shade_protocol/src/airdrop/mod.rs

Added merkle proofs to prove airdrop validity. This replaces the high gas cost of uploading the airdrop json

Airdrop merkle trees

---

README.md

Updated contract paths and instructions on running the network integration tests
Closes #147

main doc update

---

contracts/airdrop/src/test.rs
packages/network_integration/Cargo.toml
packages/network_integration/src/testnet_airdrop.rs
packages/secretcli/src/secretcli.rs

Created a quick script to deploy an airdrop contract setup to a public SN chain

Airdrop testnet deploy script

---

README.md
contracts/airdrop/Cargo.toml
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/test.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop/claim_info.rs
packages/shade_protocol/src/airdrop/mod.rs

Fixed some possible issues with dates when initializing / updating. Added a new query for total claimed.

Airdrop bug fixes

---

README.md
makefile

Improved makefile contract building and added other cargo commands to the list.

Makefile improvements

---

contracts/airdrop/README.md
contracts/airdrop/src/contract.rs
contracts/airdrop/src/query.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop/mod.rs

Allows users to check if an account airdrop has already been claimed
- ```VerifyClaimed``` verifies all of the given accounts

added account claim query

---

contracts/airdrop/Cargo.toml
contracts/airdrop/README.md
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
contracts/airdrop/src/test.rs
packages/network_integration/Cargo.toml
packages/network_integration/src/testnet_airdrop.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/Cargo.toml
packages/shade_protocol/src/airdrop/account.rs
packages/shade_protocol/src/airdrop/mod.rs

Fixes all problems with the limited terra station features, the new permits fix around these flaws.
- Permits are now compatible with terra ledger
- Fixed some account values from not appearing when querying

Airdrop permit fix

---

contracts/airdrop/Cargo.toml
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
contracts/airdrop/src/test.rs
packages/network_integration/Cargo.toml
packages/network_integration/tests/airdrop_integration.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/Cargo.toml
packages/shade_protocol/src/airdrop/account.rs
packages/shade_protocol/src/airdrop/errors.rs
packages/shade_protocol/src/airdrop/mod.rs

Implements secure viewing keys from `query-authentication` just in case permits result in issues with the high user query load
- Added viewing keys

Added viewing keys

---

contracts/treasury/src/handle.rs

Refactors some of the treasury handle functions to reduce code bloat.
- More concise matching for extraction of allocation portion and addresses
- Enacted some linter (`clippy`) suggestions

treasury: refactor some handle functions

---

contracts/mint/src/test.rs
contracts/oracle/src/test.rs

Additions to unit tests for mint and oracle, including changing mint tests over to macro, adding overflow case, and adding config unit test for oracle.e

Unit testing

---

contracts/oracle/Cargo.toml
contracts/oracle/src/query.rs
packages/shade_protocol/src/dex.rs

Moved `eval_index` onto the compat Uint512 to avoid overflow errors

fixed overflow error

---

packages/secretcli/src/cli_types.rs
packages/secretcli/src/secretcli.rs

Improved CLI Utility for Testing
- Public Storing Function to allow referring to stored contract hashes without initialization
- Add additional conditional print to more easily debug issues in test

Add Storing Contracts Utility and Verbose Error Message

---

contracts/governance/src/tests/handle/mod.rs
contracts/governance/src/tests/handle/proposal/funding.rs
contracts/governance/src/tests/handle/proposal/voting.rs
contracts/governance/src/tests/mod.rs
contracts/mint/tests/integration.rs
contracts/snip20/src/tests/mod.rs

Fixed breaking conflicts that come with the new fadroma update

updated to match fadroma's instantiate response

---

contracts/mint/Cargo.toml
packages/shade_protocol/src/contract_interfaces/snip20/mod.rs

Fixed a minor transfer config flag

transfer bug fix

---

contracts/governance/Cargo.toml
contracts/governance/src/tests/handle/mod.rs
contracts/governance/src/tests/handle/proposal/assembly_voting.rs
contracts/governance/src/tests/handle/proposal/funding.rs
contracts/governance/src/tests/handle/proposal/mod.rs
contracts/governance/src/tests/handle/proposal/voting.rs
contracts/governance/src/tests/mod.rs
contracts/mint/tests/integration.rs
contracts/query_auth/Cargo.toml
contracts/query_auth/src/tests/mod.rs
contracts/snip20/Cargo.toml
contracts/snip20/src/query.rs
contracts/snip20/src/tests/mod.rs
contracts/treasury/tests/integration.rs
contracts/treasury_manager/tests/integration.rs

refactored fadroma update

---

contracts/sky/Cargo.toml
contracts/sky/src/contract.rs
contracts/sky/src/handle.rs
contracts/sky/src/query.rs
packages/shade_protocol/Cargo.toml
packages/shade_protocol/src/contract_interfaces/dao/adapter.rs
packages/shade_protocol/src/contract_interfaces/dex/shadeswap.rs
packages/shade_protocol/src/contract_interfaces/sky/cycles.rs
packages/shade_protocol/src/contract_interfaces/sky/mod.rs

Sky migration to cosmwasm v1

---

packages/shade_protocol/src/contract_interfaces/dex/shadeswap.rs
packages/shade_protocol/src/contract_interfaces/sky/cycles.rs

added pool info query to arb pair

---

packages/cosmwasm_math_compat/Cargo.toml

Fixed a versioning issues that caused uint to cause cargo errors.

fixed minor version issue

---

contracts/treasury/Cargo.toml
contracts/treasury/src/contract.rs
contracts/treasury/src/execute.rs
contracts/treasury/src/query.rs
contracts/treasury/src/storage.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury.rs
packages/shade_protocol/src/utils/cycle.rs
packages/shade_protocol/src/utils/storage/plus/iter_map.rs
rust-toolchain

Started metrics and added migration, needs testing

Dao upgrade swenson

---

packages/multi_test/Cargo.toml
packages/multi_test/src/multi.rs
packages/shade_protocol/src/contract_interfaces/admin/helpers.rs

Admin helper function was added

Added a test admin helper function

---

contracts/treasury/src/storage.rs
contracts/treasury_manager/src/contract.rs
contracts/treasury_manager/src/execute.rs
contracts/treasury_manager/src/storage.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury_manager.rs

Treasury manager metrics, it would be nice to have some metrics for things like add/remove holders but the current metrics object doesn't really make sense to use in that way. Will have to consider this more and come up with a better solution

added treasury manager metrics

---

contracts/mock_adapter/src/contract.rs
contracts/mock_adapter/src/tests/mod.rs
contracts/scrt_staking/src/execute.rs
contracts/scrt_staking/tests/integration.rs
contracts/treasury/src/execute.rs
contracts/treasury/tests/integration.rs
contracts/treasury_manager/src/contract.rs
contracts/treasury_manager/src/execute.rs
contracts/treasury_manager/src/query.rs
contracts/treasury_manager/src/storage.rs
packages/multi_test/src/interfaces/dao.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury_manager.rs

fixed bug where treasury and treasury manager weren't accounting for unbonding tokens

fixed treasury test

---

contracts/mock_adapter/src/tests/mod.rs
contracts/treasury_manager/src/execute.rs
packages/multi_test/src/interfaces/snip20.rs
packages/multi_test/src/interfaces/treasury.rs

Migration test

---

Cargo.toml
contracts/admin/src/contract.rs
contracts/airdrop/src/contract.rs
contracts/governance/src/contract.rs
contracts/mint/src/contract.rs
contracts/peg_stability/src/contract.rs
contracts/query_auth/src/contract.rs
contracts/sky/src/contract.rs
contracts/snip20/src/contract.rs
packages/contract_derive/Cargo.toml
packages/contract_derive/src/lib.rs
packages/shade_protocol/Cargo.toml
packages/shade_protocol/src/lib.rs

Fixed an issue where entry_point assumed a direct import from cosmwasm_std instead of a package standard like shade_protocol::c_std
- entry_point imports will now be replaced by shd_entry_point

Entry point fix

---

.gitmodules

removed snip20-reference-impl

---

contracts/treasury/Cargo.toml
contracts/treasury/src/contract.rs
contracts/treasury/src/execute.rs
contracts/treasury/src/query.rs
contracts/treasury_manager/src/contract.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury.rs
packages/shade_protocol/src/utils/cycle.rs

Minor code cleanup & commenting, added 1 TODO that is a relatively easy fix

added comments and adjusted slightly

---

contracts/treasury_manager/src/execute.rs

remove instances of holding.update for load followed by update

removed holding.update

---

contracts/treasury/Cargo.toml
contracts/treasury/src/contract.rs
contracts/treasury/src/execute.rs
contracts/treasury/tests/integration/config.rs
contracts/treasury/tests/integration/migration.rs
contracts/treasury/tests/integration/mod.rs
contracts/treasury_manager/src/contract.rs
contracts/treasury_manager/src/execute.rs
contracts/treasury_manager/tests/integration/config.rs
contracts/treasury_manager/tests/integration/mod.rs
packages/multi_test/src/interfaces/treasury.rs
packages/multi_test/src/interfaces/treasury_manager.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury_manager.rs

better configs

---

contracts/treasury/src/execute.rs
contracts/treasury/tests/dao/equilibrium.rs
contracts/treasury/tests/dao/mod.rs
contracts/treasury/tests/integration/execute_errors.rs
contracts/treasury/tests/integration/migration.rs
contracts/treasury/tests/integration/mod.rs
contracts/treasury/tests/integration/non_manager_allowances.rs
packages/multi_test/src/interfaces/dao.rs
packages/multi_test/src/interfaces/snip20.rs
packages/multi_test/src/interfaces/treasury.rs

Non man allowance

---

contracts/governance/src/handle/migration.rs

Generated labels when migrating should be harder to predict

generated label should now have more entropy do accurately attack

---

Makefile.toml

Removed the accidental staking commits
`cargo install --force cargo-make`
To build the whole project for release
`cargo make build-all`
Release just one package
`cargo make release governance`
To test a package
`cargo make test governance`
Or all packages
`cargo make test-all`

Added cargo makefile

---

contracts/bonds/src/handle.rs
contracts/bonds/src/tests/handle.rs
contracts/bonds/src/tests/mod.rs
contracts/bonds/src/tests/query.rs
packages/shade_protocol/src/contract_interfaces/bonds/errors.rs

Kw001 bonds shd shd acceptance

---

contracts/bonds/src/handle.rs
contracts/bonds/src/tests/handle.rs
contracts/bonds/src/tests/mod.rs
contracts/bonds/src/tests/query.rs
packages/shade_protocol/src/contract_interfaces/bonds/errors.rs

Bonds fixes

---

contracts/bonds/src/contract.rs
contracts/bonds/src/handle.rs
contracts/bonds/src/query.rs
contracts/bonds/src/state.rs
contracts/bonds/src/tests/handle.rs
contracts/bonds/src/tests/query.rs
contracts/mock_band/src/contract.rs
packages/network_integration/src/launch/airdrop.rs
packages/shade_protocol/src/contract_interfaces/bonds/mod.rs

fixed the cherry pick

---

contracts/snip20_migration/src/contract.rs
contracts/snip20_migration/src/test.rs
packages/shade_protocol/src/contract_interfaces/snip20_migration/mod.rs

fixes token config query issues

Snip20 migration fix

---

contracts/snip20_migration/src/contract.rs
contracts/snip20_migration/tests/integration.rs

feat: migration hotfix

---

contracts/basic_staking/src/execute.rs
contracts/basic_staking/tests/single_staker_compounding.rs

fixed a bug when staking + compound, added a test for this bug

Basic staking update

---

Cargo.toml
contracts/lend-token/Cargo.toml
contracts/lend-token/src/contract.rs
contracts/lend-token/src/error.rs
contracts/lend-token/src/msg.rs
contracts/lend-token/src/state.rs
packages/lending_utils/.cargo/config
packages/lending_utils/Cargo.toml
packages/lending_utils/src/amount.rs
packages/lending_utils/src/lib.rs
packages/shade_protocol/src/contract_interfaces/snip20/mod.rs

This PR is the one that will contain all changes made during refactoring of lend-token contract from cw20 to snip20 protocols.
Getting rid of cosmwasm dependencies and replace them with shade's.
Merge it into a PR containing full copy of current lending token.

Lending: Token contract snip20 refactor
