securesecrets/shade

Cargo.lock
Cargo.toml

Original cargo config was trying to work with the rust projets in the contracts folder. This was changes to only point to the shade-contracts folder.

Cargo Config Update

---

LICENSE

This is a license change, that I think is the best for Opensource Distribution, which gives us direct references for any new applications made.
https://choosealicense.com/licenses/lgpl-3.0/#

Changing to GNU LGPLv3 for Shade licence.

---

contracts/micro_mint/README.md
contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/test.rs
packages/shade_protocol/src/micro_mint.rs

Added the ability to send non burnable tokens to a given throwaray address

Mint | secondary burn

---

contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/test.rs
packages/shade_protocol/src/micro_mint.rs

Mint | start epoch

---

contracts/micro_mint/README.md
contracts/micro_mint/src/contract.rs
contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/test.rs
packages/shade_protocol/src/micro_mint.rs

Can now remove supported assets, this will remove support to use this SNIP20 for minting but will still keep its burned amount information for future use

Mint | remove supported asset

---

contracts/staking/src/contract.rs
contracts/staking/src/handle.rs
contracts/staking/src/query.rs
contracts/staking/src/state.rs
contracts/staking/src/test.rs
packages/network_integration/src/contract_helpers/stake.rs
packages/shade_protocol/src/staking.rs

Added an efficient way to distribute value across stakers by using the staking model found in Cosmos SDK.
There are now separate unbonding queues per users so they can query their values efficiently. The old unbonding now exists for when we implement treasury rewards distribution.
To allow users to query their stake information, a very simple viewing key system was implemented

Shd stake | rewards distribution

---

Cargo.toml
tools/doc2book/Cargo.toml
tools/doc2book/README.md
tools/doc2book/src/doc2book.rs

This is a simple tool that scrapes the documentation comments and specified code blocks from a target crate. See `tools/doc2book/README.md` for more info.
It was made with the `packages/shade_protocol` crate in mind. Hopefully this should make it simple to generate the smart contract interface and usage documentation from the source code itself, where it will be easier to keep up to date.
If anyone can think of a better name (please please please) just let me know and I'll update it.

doc2book tool 

---

contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
packages/network_integration/src/contract_helpers/initializer.rs
packages/network_integration/src/contract_helpers/minter.rs
packages/network_integration/src/contract_helpers/stake.rs
packages/network_integration/src/utils.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop.rs

Added completion flags for airdrop
The flags can be added before and after deployment, each flag points to an address which will be the contracts that notify the airdrop contract when a user is eligible for that portion of the airdrop

Airdrop | completion flags

---

contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
packages/network_integration/Cargo.toml
packages/network_integration/src/contract_helpers/initializer.rs
packages/network_integration/src/main.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop.rs

Added a brute decay where the unclaimed amount gets dumped into the ```dump_address``` once ```end_date``` is reached.
Replaced minting items with sending, the contract will now have to be funded before it can start distributing rewards.
Fixed potential issue regarding token distribution when handling certain amounts with certain task percentages; token division will sometimes create very little uToken to not be claimed, to combat this when a user claims and its total percentage achieved is 100% then we just return the current claimed amount subtracted by the total rewarded amount.
Closes #128, Closes #129, Closes #135

Airdrop | minor tweaks

---

contracts/airdrop/README.md
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/lib.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
contracts/airdrop/src/test.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop/mod.rs

Added a time based decay where decayed amount will be the amount to claim multiplied by the inverse of a normalized function where ```decay_start``` is 0 and ```end_date``` is 1. This decay has been tested and added to all of the claim related functions.
Queries have also been expanded to provide decay information and an overview of the current decay multiplier.
When creating an account, the handle function will now automatically claim whatever amount you have available.
Solved an issue where integration test delays were not smart (delays are used to check for time based events like governance proposals and airdrop decay, start and end dates). They will now wait the required amount.
Closes #146

Airdrop decay

---

contracts/oracle/src/contract.rs
contracts/oracle/src/handle.rs
contracts/oracle/src/query.rs
contracts/oracle/src/test.rs
packages/shade_protocol/src/oracle.rs

Closes https://github.com/securesecrets/shade/issues/79.
A basic implementation for unregestering Secret Swap pair by symbol (specifying `symbol` seems to be sufficient since the only supported pairs are of the form: `*/SCRT` or `SSCRT/*`).

[oracle] Unregister Secret Swap pair

---

contracts/airdrop/README.md
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop/account.rs
packages/shade_protocol/src/airdrop/mod.rs
packages/shade_protocol/src/signature/mod.rs
packages/shade_protocol/src/signature/transaction.rs

Expanded ```PubKey``` traits to allow for ```HumanAddress``` and ```CanonicalAddress``` creation.
```Account``` now has its own permit, its shorter and removes the unnecessary things needed for address proof

Airdrop permit fixes

---

.gitmodules
contracts/airdrop/src/contract.rs
contracts/airdrop/src/handle.rs
contracts/airdrop/src/query.rs
contracts/airdrop/src/state.rs
contracts/airdrop/src/test.rs
packages/network_integration/src/testnet_airdrop.rs
packages/network_integration/tests/testnet_integration.rs
packages/shade_protocol/src/airdrop/mod.rs
packages/shade_protocol/src/lib.rs
packages/shade_protocol/src/math.rs

Since total claimed amount is public, malicious nodes can query this information and calculate user claimed amounts. Query now has a rounding or step amount to protect against it. Once the airdrop ```end_date``` is reached and decay amount is claimed then the real amount is exposed.

Airdrop | query protection

---

contracts/mock_band/src/contract.rs
contracts/oracle/src/contract.rs
contracts/oracle/src/query.rs
contracts/oracle/src/state.rs

Just some tidying up, 'mock-band' had an unreachable expression and the hard coded prices in oracle are no longer needed.

Oracle remove hardcoded

---

contracts/micro_mint/src/handle.rs
contracts/micro_mint/src/test.rs

Slight adjustment to mint capture so it uses 'capture *10^18` for the percentage in the same format as other decimals.

changed capture to p*(10^18)

---

contracts/airdrop/src/handle.rs
packages/shade_protocol/src/airdrop/mod.rs

The claimed amount being returned by the `account` HandleMsg was tied to account updating and not creation, resulting in it outputting `0` every time an account was creating. (Non breaking)
- Fixed `claimed` parameter returned in `account` and `claim` HandleMsgs
- Removed `unclaimed` from `account` and `claim` since theyre always going to be `0`

Airdrop | HandleMsg output bug

---

contracts/airdrop/README.md

Documentation Update: Removed "unclaimed" from response data of Account and Claim transactions.

remove unclaimed

---

packages/shade_protocol/Cargo.toml

Enables the `iterator` feature for the `cosmwasm-storage` dependency when the `storage` feature is enabled.
- Modified `shade_protocol` package feature definition in `Cargo.toml`

enable 'cosmwasm-storage/iterator' feature

---

.github/workflows/rust.yml

Now runs `cargo test` from root of project instead of per-contract so it includes tests in `packages`

now runs tests from root

---

contracts/snip20_staking/Cargo.toml
contracts/snip20_staking/src/batch.rs
contracts/snip20_staking/src/contract.rs
contracts/snip20_staking/src/expose_balance.rs
contracts/snip20_staking/src/msg.rs
contracts/snip20_staking/src/receiver.rs
contracts/snip20_staking/src/stake.rs
contracts/snip20_staking/src/stake_queries.rs
contracts/snip20_staking/src/state_staking.rs
contracts/snip20_staking/src/transaction_history.rs
packages/shade_protocol/src/snip20_staking/stake.rs

Moved away from the `ethnum` library for 256bit unsigned integers and started using the compatibility uint library. By moving into the cosmwasm 1.0 uint lib staking now has most of its math in checked functions.
- Migration to the protocol uint library
- More type safety
- Shares storage is now natively `Uint256`
- Implement errors lib
- Push for 100% math safety

Snip20 staking math update

---

packages/contract_harness/src/lib.rs

Added two flags to prevent contract harness code from building when set to build in wasm32 architecture 
- Contract harness will not compile when targeting wasm32

Contract harness fix

---

contracts/snip20/src/query.rs

Fixed bug that caused errors when no allowance was queried, It should have returned a default value

Snip20 allowance query fix

---

Cargo.toml
contracts/governance/Cargo.toml
contracts/mint/Cargo.toml
contracts/oracle/Cargo.toml
contracts/query_auth/Cargo.toml
contracts/sky/Cargo.toml
contracts/snip20/Cargo.toml
contracts/treasury/Cargo.toml
contracts/treasury_manager/Cargo.toml
packages/contract_harness/Cargo.toml
packages/contract_harness/src/lib.rs

Locks fadroma packages to commit 76867e0 and added a function that neatly assers for an ensemble execute to be ok and if not it prints the errors source (its a better design than using `.is_ok()`)
- Fadroma commit lock
- Cleaner assersions

Better assert and fadroma commit lock

---

contracts/bonds/src/handle.rs
packages/shade_protocol/src/contract_interfaces/snip20/helpers.rs

A couple lines corrected for last stages of audit.
Specifically:
-References user account solely using "from", not "sender"
-Allowance query, send_msg, and fetch_snip20 all are padded to block size 256

CON-01, HAN-10

---

packages/shade_protocol/src/lib.rs
packages/shade_protocol/src/utils/storage/plus/iter_item.rs
packages/shade_protocol/src/utils/storage/plus/iter_map.rs
packages/shade_protocol/src/utils/storage/plus/mod.rs

Taking into consideration the cosmwasm limitations, Item and Map now have equivalents for iteration
- Added an Item equivalent that lets you iterate the members like if it was an array
- Added a Map equivalent that does the same as the IterItem
- The `::new()` function isnt working because I need to build a string at compile time, still need to find a solution for this

Map and Item storage iterator

---

packages/shade_protocol/src/utils/cycle.rs
packages/shade_protocol/src/utils/mod.rs
packages/shade_protocol/src/utils/storage/plus/iter_item.rs
packages/shade_protocol/src/utils/storage/plus/iter_map.rs
packages/shade_protocol/src/utils/storage/plus/mod.rs
packages/shade_protocol/src/utils/storage/plus/period_storage.rs

Storage type to organize data by an associated datetime.
The chosen type `T` will be used to store in various `Map<Timestamp, Vec<T>>` storages.
`all` is a `{ seconds: Vec<T> }`
`recent` is a list of `[ seconds, ...]` to correlate to `all` in order to pull "unflushed" elements
When `flush` is called, it will iterate `recent` and organize into dated storages, with formatted datetime strings as keys
Keys:
`hour`: `%Y-%m-%dT%h`
`day`: `%Y-%m-%d`
`month`: `%Y-%m`
The basic use case I have so far is for "metrics" (currently implemented in `treasury`). This allows all storage to be queryable based on a datetime from the client, allowing for smaller bits of targeted data depending on what the front-end needs.
Added pagination can be performed by the client (may be useful to add in this object) …

Period storage

---

contracts/treasury/src/contract.rs
contracts/treasury/src/execute.rs
contracts/treasury/src/storage.rs
contracts/treasury/tests/wrap_integration.rs
contracts/treasury_manager/src/execute.rs
packages/shade_protocol/src/contract_interfaces/dao/treasury.rs
packages/shade_protocol/src/utils/wrap.rs

Treasury can now `WrapCoins {}` to wrap all its L1 coins that have a configured wrap token, configured with `RegisterWrap { denom, contract }`
Tested with `uscrt` as well as a `fail` denom that it cannot successfully wrap.
Need to import `snip20-reference-impl` on the branch `ibc` and rework test to allow any number of denoms configured in tests

Treasury wrap

---

contracts/bonds/src/handle.rs
contracts/bonds/src/tests/mod.rs

Signed-off-by: Kyle Wahlberg <kyle.s.wahlberg@gmail.com>
Updated oracle query to use snip20 names, rather than symbols. Test updated to reflect this change by using aliases.

Symbol -> Name for oracle queries

---

packages/shade_protocol/src/utils/storage/plus/iter_item.rs
packages/shade_protocol/src/utils/storage/plus/iter_map.rs

"Fixed" the issue with not being able to concatenate strings on the constant function.
- Iter storage now has a macro wrapper to get by the concatenation limits when handling variables.

Iter storage constant string fix
